// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package pkg is a generated GoMock package.
package pkg

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetricInterface is a mock of MetricInterface interface.
type MockMetricInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMetricInterfaceMockRecorder
}

// MockMetricInterfaceMockRecorder is the mock recorder for MockMetricInterface.
type MockMetricInterfaceMockRecorder struct {
	mock *MockMetricInterface
}

// NewMockMetricInterface creates a new mock instance.
func NewMockMetricInterface(ctrl *gomock.Controller) *MockMetricInterface {
	mock := &MockMetricInterface{ctrl: ctrl}
	mock.recorder = &MockMetricInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricInterface) EXPECT() *MockMetricInterfaceMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockMetricInterface) Count(name string, value int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Count", name, value)
}

// Count indicates an expected call of Count.
func (mr *MockMetricInterfaceMockRecorder) Count(name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockMetricInterface)(nil).Count), name, value)
}

// Duration mocks base method.
func (m *MockMetricInterface) Duration(timestamp int64, name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Duration", timestamp, name)
}

// Duration indicates an expected call of Duration.
func (mr *MockMetricInterfaceMockRecorder) Duration(timestamp, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Duration", reflect.TypeOf((*MockMetricInterface)(nil).Duration), timestamp, name)
}

// Gauge mocks base method.
func (m *MockMetricInterface) Gauge(name string, value float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Gauge", name, value)
}

// Gauge indicates an expected call of Gauge.
func (mr *MockMetricInterfaceMockRecorder) Gauge(name, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gauge", reflect.TypeOf((*MockMetricInterface)(nil).Gauge), name, value)
}

// Increment mocks base method.
func (m *MockMetricInterface) Increment(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Increment", name)
}

// Increment indicates an expected call of Increment.
func (mr *MockMetricInterfaceMockRecorder) Increment(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Increment", reflect.TypeOf((*MockMetricInterface)(nil).Increment), name)
}
